import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signOut } from "next-auth/react";
import { trpc } from "../../utils/trpc";
import ProtectedPage from "../../utils/ProtectedPage";

import MonthsCard from "../../components/MonthsCard";

const Home: NextPage = () => {
  const availableMonths = trpc.datas.getMeses.useQuery();

  console.log("opa", availableMonths.data);

  return (
    <>
      <Head>
        <title>Acad Tracker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-1 gap-6 p-8 md:grid-cols-2 lg:grid-cols-3 xl:lg:grid-cols-4">
        {availableMonths.data?.map(({ year, month }, index) => {
          return (
            <Link
              href={`http://localhost:3000/progresso/${year}?mes=${month}`}
              key={index}
            >
              <MonthsCard year={year} month={month} />
            </Link>
          );
        })}
      </div>

      <main className="flex flex-col items-center">
        <h1 className="text-lg font-bold">Você esta logado</h1>
        <button
          className=" w-1/4 rounded border bg-slate-50 px-4 py-2 font-bold shadow-lg"
          onClick={() => signOut()}
        >
          Sign out
        </button>
      </main>
    </>
  );
};

function ProtectedHome() {
  return <ProtectedPage Page={Home} />;
}

export default ProtectedHome;
