import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";
import ProtectedPage from "../utils/ProtectedPage";

const Home: NextPage = () => {
  const criar = trpc.example.hello.useMutation();
  return (
    <>
      <Head>
        <title>Acad Tracker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center">
        <h1 className="text-lg font-bold">Você esta logado</h1>
        <button
          className=" w-1/4 rounded border-2 px-4 py-2 font-bold"
          onClick={() => signOut()}
        >
          Sign out
        </button>
        <button
          className=" w-1/4 rounded border-2 px-4 py-2 font-bold"
          onClick={() => criar.mutate()}
        >
          criar bagulho
        </button>
      </main>
    </>
  );
};

function ProtectedHome() {
  return <ProtectedPage Page={Home} />;
}

export default ProtectedHome;
